-- DATABASE: NOPAYNOGAME

-- INSERT FOR TABLE DOM_CONSOLE
--COD_CONSOLE VARCHAR(4) NOT NULL
--DESC_CONSOLE VARCHAR(45) NOT NULL
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ();

-- INSERT FOR TABLE DOM_GENRE
--COD_GENRE VARCHAR(4) NOT NULL
--DESC_GENRE VARCHAR(45) NOT NULL
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ();

-- INSERT FOR TABLE DOM_PAYMENT
--COD_PAYMENT VARCHAR(4) NOT NULL
--DESC_PAYMENT VARCHAR(45) NOT NULL
INSERT INTO DOM_PAYMENT (COD_PAYMENT, DESC_PAYMENT)
VALUES ();

-- INSERT FOR TABLE DOM_ROLE
--COD_ROLE CHAR(3) NOT NULL
--DESC_ROLE VARCHAR(45) NOT NULL
INSERT INTO DOM_ROLE (COD_ROLE, DESC_ROLE)
VALUES ();

-- INSERT FOR TABLE GAMES
-- COD_GAME VARCHAR(4) NOT NULL
-- TITLE VARCHAR(45) NOT NULL
-- PRICE INT(11) NOT NULL
-- COD_CONSOLE VARCHAR(4)  NOT NULL
-- PRICE_ON_SALE INT(11) NOT NULL (>= 0)
-- FLAG_SALE CHAR(1) NOT NULL (Y-N)
-- FLAG_NEWS CHAR(1) DEFAULT 'Y' NOT NULL (Y-N)
INSERT INTO GAMES (COD_GAME, TITLE, PRICE, COD_CONSOLE, PRICE_ON_SALE, FLAG_SALE, FLAG_NEWS)
VALUES ();

-- INSERT FOR TABLE GAME_GENRE
-- COD_GAME VARCHAR(4) NOT NULL
-- COD_GENRE VARCHAR(4) NOT NULL
INSERT INTO GAME_GENRE (COD_GAME, COD_GENRE)
VALUES ();

-- INSERT FOR TABLE USERS
-- NAME VARCHAR(45) NOT NULL
-- SURNAME VARCHAR(45) NOT NULL
-- ADDRESS VARCHAR(45) NOT NULL
-- PHONE VARCHAR(10) NOT NULL
-- USERNAME VARCHAR(11) NOT NULL
-- PASSSWORD VARCHAR(16) NOT NULL
-- COD_ROLE CHAR(3) NOT NULL
INSERT INTO USERS (NAME, SURNAME, ADDRESS, PHONE, USERNAME, PASSSWORD, COD_ROLE)
VALUES ();

-- INSERT FOR TABLE ORDERS
-- ID_USER INT(11) NOT NULL
-- COD_PAYMENT VARCHAR(4) NOT NULL
INSERT INTO ORDERS (ID_USER, COD_PAYMENT)
VALUES ();

-- INSERT FOR TABLE GAME_ORDER
-- ID_ORDER INT(11) NOT NULL
-- COD_GAME VARCHAR(4) NOT NULL
-- QUANTITY INT(11) NOT NULL
INSERT INTO GAME_ORDER (ID_ORDER, COD_GAME, QUANTITY)
VALUES ();

-- INSERT FOR TABLE REVIEW
-- COD_GAME VARCHAR(4) NOT NULL
-- ID_USER INT(11) NOT NULL
-- STARS INT(11) NOT NULL
-- COMMENT_TEXT VARCHAR(2000)
INSERT INTO REVIEW (COD_GAME, ID_USER, STARS, COMMENT_TEXT)
VALUES ();

-- INSERT FOR TABLE WAREHOUSE
-- COD_WAREHOUSE CHAR(3) NOT NULL
-- ADDRESS VARCHAR(45) NOT NULL
-- PHONE VARCHAR(45) NOT NULL
INSERT INTO WAREHOUSE (COD_WAREHOUSE, ADDRESS, PHONE)
VALUES ();

-- INSERT FOR TABLE GAME_WAREHOUSE
-- QUANTITY INT(11) NOT NULL
-- COD_WAREHOUSE CHAR(3) NOT NULL
-- COD_GAME VARCHAR(4) NOT NULL
INSERT INTO GAME_WAREHOUSE (QUANTITY, COD_WAREHOUSE, COD_GAME)
VALUES ();
