-- DATABASE: NOPAYNOGAME

-- INSERT FOR TABLE DOM_CONSOLE
--COD_CONSOLE VARCHAR(4) NOT NULL
--DESC_CONSOLE VARCHAR(45) NOT NULL
--INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
--VALUES ('','');

INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO01','XBOX ONE X');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO02','XBOX ONE S');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO03','XBOX ONE');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO04','PS4');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO05','PS4 PRO');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO06','PC');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO07','NINTENDO WII U');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO08','NINTENDO SWITCH');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO09','NINTENDO 3DS');
INSERT INTO DOM_CONSOLE (COD_CONSOLE, DESC_CONSOLE)
VALUES ('CO10','PSVITA');


-- INSERT FOR TABLE DOM_GENRE
--COD_GENRE VARCHAR(4) NOT NULL
--DESC_GENRE VARCHAR(45) NOT NULL
--INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
--VALUES ('','');

INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE01','AZIONE');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE02','AVVENTURA');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE03','SPORT');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE04','SPARATUTTO');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE05','FPS');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE06','MMO');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE07','RPG');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE08','PICCHIADURO');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE09','ARENA');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE10','MOBA');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE11','ROMPICAPO');
INSERT INTO DOM_GENRE (COD_GENRE, DESC_GENRE)
VALUES ('GE12','PUZZLE');


-- INSERT FOR TABLE DOM_PAYMENT
--COD_PAYMENT VARCHAR(4) NOT NULL
--DESC_PAYMENT VARCHAR(45) NOT NULL
--INSERT INTO DOM_PAYMENT (COD_PAYMENT, DESC_PAYMENT)
--VALUES ('','');

INSERT INTO DOM_PAYMENT (COD_PAYMENT, DESC_PAYMENT)
VALUES ('PAY1','PAYPAL');
INSERT INTO DOM_PAYMENT (COD_PAYMENT, DESC_PAYMENT)
VALUES ('PAY2','BONIFICO');
INSERT INTO DOM_PAYMENT (COD_PAYMENT, DESC_PAYMENT)
VALUES ('PAY3','CARTA DI CREDITO');
INSERT INTO DOM_PAYMENT (COD_PAYMENT, DESC_PAYMENT)
VALUES ('PAY4','CONTRASSEGNO');


-- INSERT FOR TABLE DOM_ROLE
--COD_ROLE CHAR(3) NOT NULL
--DESC_ROLE VARCHAR(45) NOT NULL
--INSERT INTO DOM_ROLE (COD_ROLE, DESC_ROLE)
--VALUES ('','');

INSERT INTO DOM_ROLE (COD_ROLE, DESC_ROLE)
VALUES ('ROL1','USER');
INSERT INTO DOM_ROLE (COD_ROLE, DESC_ROLE)
VALUES ('ROL2','MAGAZZINIERE');
INSERT INTO DOM_ROLE (COD_ROLE, DESC_ROLE)
VALUES ('ROL3','AMMINISTRATORE');
INSERT INTO DOM_ROLE (COD_ROLE, DESC_ROLE)
VALUES ('ROL4','SUPERUSER');


-- INSERT FOR TABLE GAMES
-- COD_GAME VARCHAR(4) NOT NULL
-- TITLE VARCHAR(45) NOT NULL
-- PRICE INT(11) NOT NULL
-- COD_CONSOLE VARCHAR(4)  NOT NULL
-- PRICE_ON_SALE INT(11) NOT NULL (>= 0)
-- FLAG_SALE CHAR(1) NOT NULL (Y-N)
-- FLAG_NEWS CHAR(1) DEFAULT 'Y' NOT NULL (Y-N)
INSERT INTO GAMES (COD_GAME, TITLE, PRICE, COD_CONSOLE, PRICE_ON_SALE, FLAG_SALE, FLAG_NEWS)
VALUES ();

-- INSERT FOR TABLE GAME_GENRE
-- COD_GAME VARCHAR(4) NOT NULL
-- COD_GENRE VARCHAR(4) NOT NULL
INSERT INTO GAME_GENRE (COD_GAME, COD_GENRE)
VALUES ('','');

-- INSERT FOR TABLE USERS
-- NAME VARCHAR(45) NOT NULL
-- SURNAME VARCHAR(45) NOT NULL
-- ADDRESS VARCHAR(45) NOT NULL
-- PHONE VARCHAR(10) NOT NULL
-- USERNAME VARCHAR(11) NOT NULL
-- PASSSWORD VARCHAR(16) NOT NULL
-- COD_ROLE CHAR(3) NOT NULL
--INSERT INTO USERS (NAME, SURNAME, ADDRESS, PHONE, USERNAME, PASSSWORD, COD_ROLE)
--VALUES ('', '', '', , '', '', '');

INSERT INTO USERS (NAME, SURNAME, ADDRESS, PHONE, USERNAME, PASSSWORD, COD_ROLE)
VALUES ('Pino', 'Abete', 'via Paradiso 666', 9801234567, 'superuser', 'superuser', 'ROL4');
INSERT INTO USERS (NAME, SURNAME, ADDRESS, PHONE, USERNAME, PASSSWORD, COD_ROLE)
VALUES ('Utente', 'Normale', 'via Fossa 40', 1234567890, 'utente', 'utente', 'ROL1');
INSERT INTO USERS (NAME, SURNAME, ADDRESS, PHONE, USERNAME, PASSSWORD, COD_ROLE)
VALUES ('Luca', 'Magazziniere', 'via Pozzo 1', 1234569870, 'magazziniere', 'magazziniere', 'ROL2');
INSERT INTO USERS (NAME, SURNAME, ADDRESS, PHONE, USERNAME, PASSSWORD, COD_ROLE)
VALUES ('Tobia', 'Amministratore', 'via Cielo 234', 9871236540, 'amministratore', 'amministratore', 'ROL3');



-- INSERT FOR TABLE ORDERS
-- ID_USER INT(11) NOT NULL
-- COD_PAYMENT VARCHAR(4) NOT NULL
INSERT INTO ORDERS (ID_USER, COD_PAYMENT)
VALUES ( ,'');

-- INSERT FOR TABLE GAME_ORDER
-- ID_ORDER INT(11) NOT NULL
-- COD_GAME VARCHAR(4) NOT NULL
-- QUANTITY INT(11) NOT NULL
INSERT INTO GAME_ORDER (ID_ORDER, COD_GAME, QUANTITY)
VALUES ();

-- INSERT FOR TABLE REVIEW
-- COD_GAME VARCHAR(4) NOT NULL
-- ID_USER INT(11) NOT NULL
-- STARS INT(11) NOT NULL
-- COMMENT_TEXT VARCHAR(2000)
INSERT INTO REVIEW (COD_GAME, ID_USER, STARS, COMMENT_TEXT)
VALUES ();

-- INSERT FOR TABLE WAREHOUSE
-- COD_WAREHOUSE CHAR(3) NOT NULL
-- ADDRESS VARCHAR(45) NOT NULL
-- PHONE VARCHAR(45) NOT NULL
--INSERT INTO WAREHOUSE (COD_WAREHOUSE, ADDRESS, PHONE)
--VALUES ('', '', '');

INSERT INTO WAREHOUSE (COD_WAREHOUSE, ADDRESS, PHONE)
VALUES ('WH1', 'via Macello 1', '1236547890');
INSERT INTO WAREHOUSE (COD_WAREHOUSE, ADDRESS, PHONE)
VALUES ('WH2', 'via Budello 2', '9874563210');
INSERT INTO WAREHOUSE (COD_WAREHOUSE, ADDRESS, PHONE)
VALUES ('WH3', 'via Fretello 3', '0147852369');


-- INSERT FOR TABLE GAME_WAREHOUSE
-- QUANTITY INT(11) NOT NULL
-- COD_WAREHOUSE CHAR(3) NOT NULL
-- COD_GAME VARCHAR(4) NOT NULL
INSERT INTO GAME_WAREHOUSE (QUANTITY, COD_WAREHOUSE, COD_GAME)
VALUES ();
